"""Add Contact model and joined_at to GroupMember

Revision ID: 4e76c8a94ee2
Revises: 52ee61b79a6b
Create Date: 2025-12-01 01:04:09.773389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e76c8a94ee2'
down_revision = '52ee61b79a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joined_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_member', schema=None) as batch_op:
        batch_op.drop_column('joined_at')

    # ### end Alembic commands ###
